; Original Chinese overrides for the Spark Mate installer; other diagnostics use the compiler defaults.
[LangOptions]
LanguageName=简体中文
LanguageID=$0804
LanguageCodePage=0
DialogFontName=Microsoft YaHei UI
DialogFontSize=9

[Messages]
SetupAppTitle=安装程序
SetupWindowTitle=安装 - %1
UninstallAppTitle=卸载程序
UninstallAppFullTitle=卸载 %1
InformationTitle=提示
ConfirmTitle=确认
ErrorTitle=错误
SetupAlreadyRunning=安装程序已经在运行。
ExitSetupTitle=退出安装
ExitSetupMessage=安装尚未完成。现在退出将不会完成安装。%n%n确定退出吗？
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonNo=否(&N)
ButtonFinish=完成(&F)
ButtonBrowse=浏览(&B)...
ButtonWizardBrowse=浏览(&R)...
ClickNext=点击“下一步”继续，或点击“取消”退出安装。
BrowseDialogTitle=选择文件夹
BrowseDialogLabel=请选择一个文件夹，然后点击“确定”。
WelcomeLabel1=欢迎安装 [name]
WelcomeLabel2=即将在这台电脑上安装 [name/ver]。%n%n软件免费使用。账号和设置保存在本机。
WizardLicense=开源许可
LicenseLabel=请阅读以下开源许可。
LicenseLabel3=继续安装前，请阅读项目的 MIT 开源许可。第三方组件保留各自许可，详见安装目录中的说明。
LicenseAccepted=我接受该许可(&A)
LicenseNotAccepted=我不接受该许可(&D)
WizardSelectDir=选择安装位置
SelectDirDesc=将 [name] 安装到哪里？
SelectDirLabel3=安装程序将把 [name] 安装到以下文件夹。
SelectDirBrowseLabel=点击“下一步”继续。如需更换位置，请点击“浏览”。
DiskSpaceGBLabel=至少需要 [gb] GB 可用磁盘空间。
DiskSpaceMBLabel=至少需要 [mb] MB 可用磁盘空间。
DirExistsTitle=文件夹已存在
DirExists=文件夹：%n%n%1%n%n已存在。是否继续安装到此处？
WizardSelectTasks=附加选项
SelectTasksDesc=选择需要的快捷方式。
SelectTasksLabel2=选择安装 [name] 时要执行的附加操作，然后点击“下一步”。
WizardReady=准备安装
ReadyLabel1=现在可以开始安装 [name]。
ReadyLabel2a=点击“安装”开始，或点击“上一步”检查设置。
ReadyLabel2b=点击“安装”开始。
ReadyMemoDir=安装位置：
ReadyMemoGroup=开始菜单：
ReadyMemoTasks=附加操作：
WizardPreparing=准备安装
PreparingDesc=正在准备安装 [name]。
WizardInstalling=正在安装
InstallingLabel=正在安装 [name]，请稍候。
FinishedHeadingLabel=[name] 安装完成
FinishedLabelNoIcons=[name] 已安装到这台电脑。点击“完成”关闭安装程序。
FinishedLabel=[name] 已安装到这台电脑。可以从开始菜单打开程序。
ClickFinish=点击“完成”退出安装。
StatusExtractFiles=正在释放文件...
StatusCreateIcons=正在创建快捷方式...
StatusRunProgram=正在打开程序...
StatusSavingUninstall=正在保存卸载信息...
UninstallConfirm=确定要卸载 %1 及其程序组件吗？%n%n个人设置和发送记录将保留在本机。
UninstalledAll=%1 已卸载。个人数据仍保留在本机。
